# netlify.toml

# Add the Inngest plugin configuration
[[plugins]]
  package = "netlify-plugin-inngest"
  # Optional inputs if defaults aren't suitable:
  # [plugins.inputs]
  #   host = "https://my-specific-domain.com"
  #   path = "/api/inngest" # Default is /.netlify/functions/inngest

# Base settings for all contexts
[build]
  # Command to build your site: cd into frontend, install deps, then build
  command = "cd frontend && npm install && npm run build"
  # Directory (relative to root) containing deploy-ready assets
  publish = "frontend/dist"
  # Directory containing Netlify functions
  functions = "netlify/functions"

# Optional: Specify Node.js bundler for functions
# This might help resolve module issues like the one with inngest/netlify
[functions]
  node_bundler = "esbuild"

# Development server settings for Vite
[dev]
  # Explicitly run the dev script from the frontend directory
  command = "npm run dev --prefix frontend"
  framework = "vite"
  # viteProjectDirectory = "frontend" # Commented out
  # Port the frontend dev server (Vite) runs on
  targetPort = 5173 # Use default Vite port
  # Serve static assets from build output if needed (can sometimes help)
  publish = "frontend/dist"

# Redirects and rewrites (Essential for SPAs)
[[redirects]]
  from = "/api/graphql"
  # Use the full URL for the function endpoint
  to = "http://localhost:8888/.netlify/functions/graphql"
  status = 200
  # Force this rule to apply even if a file exists at the 'from' path (optional, but can help)
  # force = true

# SPA fallback: Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 